name: Node.js CD

on:
  workflow_run:
    workflows: [ "Node.js CI" ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['21.7.2']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: git pull origin master
